"""
Phase 5: Presentation Layer (User Output)

This phase handles the user-friendly presentation of restaurant recommendations
generated by the LLM in Phase 4. It provides rendering capabilities for displaying
top K results with restaurant details and AI-generated explanations.
"""

__version__ = "0.1.0"
