[client]
toolbarMode = "minimal"

[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#E23744"
backgroundColor = "#0c0c0e"
secondaryBackgroundColor = "#16161a"
textColor = "#f4f4f5"
font = "sans serif"
